version: '3.7'

x-common-props: &common-props
    build:
        context: ./
        target: base
    working_dir: /base
    volumes:
        - ./:/base
        - node_modules:/base/node_modules

services:
    yarn:
        <<: *common-props
        entrypoint: yarn
    dev:
        <<: *common-props
        ports:
            - '3000:3000'
        command: yarn dev
        depends_on:
            - yarn
volumes:
    node_modules:
