import { COMPONENT_HIGHLIGHT, MOUSE_TRACK } from 'components/AppContext/constants'
import styled, { css } from 'styled-components'
import { useContext } from 'react'
import { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Users from 'components/Users/Users'
import AppContext from 'components/AppContext/AppContext'
import styles from 'styles/Home.module.css'

export type PositionValue = null | number

interface InteractiveComponents {
  isFocused?: boolean
}

const INPUT_FIELD_ID = 'inputField'

const FormGroup = styled.div<InteractiveComponents>(
  ({ isFocused }) => css`
    position: relative;
    display: flex;
    justify-content: space-around;
    
    > * {
      margin-left: 8px;
    }

  ${isFocused && css`
    &::after {
      content: '';  
      width: 8px;
      height: 8px;
      border-radius: 4px;
      display: block;
      background: green;
      position: absolute;
      top: -4px;
      right: -4px;
    }
  `}
  `,
)

const HighlightInput = styled.input<InteractiveComponents>(
  ({ isFocused }) => css`
    border: 3px solid ${isFocused ? 'lightgreen' : 'black'};
    
    &:disabled {
      cursor: not-allowed;
      background: grey;
    }
  `,
)

const Home: NextPage = () => {
  const { helpers, state } = useContext(AppContext)
  const { [MOUSE_TRACK]: position = {}, [COMPONENT_HIGHLIGHT]: components = {} } = state
  const { handleComponentBlurred, handleComponentFocused } = helpers || {}

  return (
    <>
      <Users />
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome 🏖
          </h1>

          <div className={styles.description}>
            You can get started by:
            <div className={styles.body}>
              <ol>
                <li>Adding a new cookie to your browser with the chrome plugin
                  <code className={styles.code}>
                    <a href="https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg" target="__blank">
                      EditThisCookie
                    </a>
                  </code>.
                </li>
                <li>
                  Using the plugin from the step 1 you can add a new cookie with the following details:
                  <ul>
                    <li><strong>name</strong> <code className={styles.code}>user_email</code>.</li>
                    <li>in <strong>value</strong> you will add your email (or whatever you want to be seem by others).</li>
                    <li>Change the option <strong>No restriction</strong> to <code className={styles.code}>strict</code>.</li>
                    <li>And mark ✅ the option bellow <code className={styles.code}>session</code>.</li>
                  </ul>
                </li>
                <li>
                  Refresh your browser.
                </li>
                <li>
                  Start moving your mouse, or try to edit the <code className={styles.code}>Description</code> field bellow if nobody else got the lock 🔐 😜.
                </li>
              </ol>
            </div>
          </div>

          <FormGroup isFocused={!!components[INPUT_FIELD_ID]}>
            <label htmlFor={INPUT_FIELD_ID}>Description</label>
            <HighlightInput
              id={INPUT_FIELD_ID}
              disabled={!!components[INPUT_FIELD_ID]}
              isFocused={!!components[INPUT_FIELD_ID]}
              onBlur={handleComponentBlurred}
              onFocus={handleComponentFocused}
              type="text"
            />
          </FormGroup>

        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    </>
  )
}

export default Home
